// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersRequest) Reset()         { *m = UsersRequest{} }
func (m *UsersRequest) String() string { return proto.CompactTextString(m) }
func (*UsersRequest) ProtoMessage()    {}
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{0}
}

func (m *UsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersRequest.Unmarshal(m, b)
}
func (m *UsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersRequest.Marshal(b, m, deterministic)
}
func (m *UsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersRequest.Merge(m, src)
}
func (m *UsersRequest) XXX_Size() int {
	return xxx_messageInfo_UsersRequest.Size(m)
}
func (m *UsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsersRequest proto.InternalMessageInfo

type UserHousesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserHousesRequest) Reset()         { *m = UserHousesRequest{} }
func (m *UserHousesRequest) String() string { return proto.CompactTextString(m) }
func (*UserHousesRequest) ProtoMessage()    {}
func (*UserHousesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{1}
}

func (m *UserHousesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHousesRequest.Unmarshal(m, b)
}
func (m *UserHousesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHousesRequest.Marshal(b, m, deterministic)
}
func (m *UserHousesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHousesRequest.Merge(m, src)
}
func (m *UserHousesRequest) XXX_Size() int {
	return xxx_messageInfo_UserHousesRequest.Size(m)
}
func (m *UserHousesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHousesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserHousesRequest proto.InternalMessageInfo

func (m *UserHousesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UserHouse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	HouseId              string   `protobuf:"bytes,3,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	HouseLocation        string   `protobuf:"bytes,4,opt,name=house_location,json=houseLocation,proto3" json:"house_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserHouse) Reset()         { *m = UserHouse{} }
func (m *UserHouse) String() string { return proto.CompactTextString(m) }
func (*UserHouse) ProtoMessage()    {}
func (*UserHouse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{2}
}

func (m *UserHouse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHouse.Unmarshal(m, b)
}
func (m *UserHouse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHouse.Marshal(b, m, deterministic)
}
func (m *UserHouse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHouse.Merge(m, src)
}
func (m *UserHouse) XXX_Size() int {
	return xxx_messageInfo_UserHouse.Size(m)
}
func (m *UserHouse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHouse.DiscardUnknown(m)
}

var xxx_messageInfo_UserHouse proto.InternalMessageInfo

func (m *UserHouse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserHouse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserHouse) GetHouseId() string {
	if m != nil {
		return m.HouseId
	}
	return ""
}

func (m *UserHouse) GetHouseLocation() string {
	if m != nil {
		return m.HouseLocation
	}
	return ""
}

type UserHousesResponse struct {
	UserHouses           []*UserHouse `protobuf:"bytes,1,rep,name=user_houses,json=userHouses,proto3" json:"user_houses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserHousesResponse) Reset()         { *m = UserHousesResponse{} }
func (m *UserHousesResponse) String() string { return proto.CompactTextString(m) }
func (*UserHousesResponse) ProtoMessage()    {}
func (*UserHousesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{3}
}

func (m *UserHousesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserHousesResponse.Unmarshal(m, b)
}
func (m *UserHousesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserHousesResponse.Marshal(b, m, deterministic)
}
func (m *UserHousesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserHousesResponse.Merge(m, src)
}
func (m *UserHousesResponse) XXX_Size() int {
	return xxx_messageInfo_UserHousesResponse.Size(m)
}
func (m *UserHousesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserHousesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserHousesResponse proto.InternalMessageInfo

func (m *UserHousesResponse) GetUserHouses() []*UserHouse {
	if m != nil {
		return m.UserHouses
	}
	return nil
}

type User struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Name                 string               `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{4}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersResponse) Reset()         { *m = UsersResponse{} }
func (m *UsersResponse) String() string { return proto.CompactTextString(m) }
func (*UsersResponse) ProtoMessage()    {}
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{5}
}

func (m *UsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResponse.Unmarshal(m, b)
}
func (m *UsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResponse.Marshal(b, m, deterministic)
}
func (m *UsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResponse.Merge(m, src)
}
func (m *UsersResponse) XXX_Size() int {
	return xxx_messageInfo_UsersResponse.Size(m)
}
func (m *UsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResponse proto.InternalMessageInfo

func (m *UsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{6}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HousesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HousesRequest) Reset()         { *m = HousesRequest{} }
func (m *HousesRequest) String() string { return proto.CompactTextString(m) }
func (*HousesRequest) ProtoMessage()    {}
func (*HousesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{7}
}

func (m *HousesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HousesRequest.Unmarshal(m, b)
}
func (m *HousesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HousesRequest.Marshal(b, m, deterministic)
}
func (m *HousesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HousesRequest.Merge(m, src)
}
func (m *HousesRequest) XXX_Size() int {
	return xxx_messageInfo_HousesRequest.Size(m)
}
func (m *HousesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HousesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HousesRequest proto.InternalMessageInfo

type CreateHouseRequest struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	OwnerId              string   `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHouseRequest) Reset()         { *m = CreateHouseRequest{} }
func (m *CreateHouseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHouseRequest) ProtoMessage()    {}
func (*CreateHouseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{8}
}

func (m *CreateHouseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHouseRequest.Unmarshal(m, b)
}
func (m *CreateHouseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHouseRequest.Marshal(b, m, deterministic)
}
func (m *CreateHouseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHouseRequest.Merge(m, src)
}
func (m *CreateHouseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHouseRequest.Size(m)
}
func (m *CreateHouseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHouseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHouseRequest proto.InternalMessageInfo

func (m *CreateHouseRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *CreateHouseRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type HousesResponse struct {
	Houses               []*House `protobuf:"bytes,1,rep,name=houses,proto3" json:"houses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HousesResponse) Reset()         { *m = HousesResponse{} }
func (m *HousesResponse) String() string { return proto.CompactTextString(m) }
func (*HousesResponse) ProtoMessage()    {}
func (*HousesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{9}
}

func (m *HousesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HousesResponse.Unmarshal(m, b)
}
func (m *HousesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HousesResponse.Marshal(b, m, deterministic)
}
func (m *HousesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HousesResponse.Merge(m, src)
}
func (m *HousesResponse) XXX_Size() int {
	return xxx_messageInfo_HousesResponse.Size(m)
}
func (m *HousesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HousesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HousesResponse proto.InternalMessageInfo

func (m *HousesResponse) GetHouses() []*House {
	if m != nil {
		return m.Houses
	}
	return nil
}

type House struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OwnerId              string               `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Location             string               `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *House) Reset()         { *m = House{} }
func (m *House) String() string { return proto.CompactTextString(m) }
func (*House) ProtoMessage()    {}
func (*House) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ff5ab49d8a5fcc4, []int{10}
}

func (m *House) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_House.Unmarshal(m, b)
}
func (m *House) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_House.Marshal(b, m, deterministic)
}
func (m *House) XXX_Merge(src proto.Message) {
	xxx_messageInfo_House.Merge(m, src)
}
func (m *House) XXX_Size() int {
	return xxx_messageInfo_House.Size(m)
}
func (m *House) XXX_DiscardUnknown() {
	xxx_messageInfo_House.DiscardUnknown(m)
}

var xxx_messageInfo_House proto.InternalMessageInfo

func (m *House) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *House) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *House) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *House) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *House) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func init() {
	proto.RegisterType((*UsersRequest)(nil), "pb.UsersRequest")
	proto.RegisterType((*UserHousesRequest)(nil), "pb.UserHousesRequest")
	proto.RegisterType((*UserHouse)(nil), "pb.UserHouse")
	proto.RegisterType((*UserHousesResponse)(nil), "pb.UserHousesResponse")
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*UsersResponse)(nil), "pb.UsersResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "pb.CreateUserRequest")
	proto.RegisterType((*HousesRequest)(nil), "pb.HousesRequest")
	proto.RegisterType((*CreateHouseRequest)(nil), "pb.CreateHouseRequest")
	proto.RegisterType((*HousesResponse)(nil), "pb.HousesResponse")
	proto.RegisterType((*House)(nil), "pb.House")
}

func init() {
	proto.RegisterFile("pb/service.proto", fileDescriptor_6ff5ab49d8a5fcc4)
}

var fileDescriptor_6ff5ab49d8a5fcc4 = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xe3, 0x54,
	0x14, 0xd6, 0x4d, 0xd2, 0x36, 0x39, 0x69, 0x32, 0xed, 0x1d, 0xa6, 0x04, 0x23, 0x0d, 0xc6, 0x08,
	0x31, 0xaa, 0x54, 0xbb, 0xa4, 0xdd, 0x30, 0xac, 0x4a, 0x41, 0x99, 0x00, 0x42, 0xc8, 0x05, 0x21,
	0xb1, 0x89, 0x6e, 0xec, 0x83, 0x63, 0xa9, 0xf6, 0x35, 0xbe, 0xd7, 0x93, 0xa9, 0x10, 0x1b, 0x78,
	0x03, 0xd8, 0xb1, 0xe2, 0x09, 0x58, 0xf0, 0x0c, 0xbc, 0x01, 0xaf, 0xc0, 0x96, 0x3d, 0x4b, 0xe4,
	0x73, 0x6d, 0xc7, 0x69, 0x84, 0x60, 0xc9, 0xce, 0xe7, 0xe7, 0xfb, 0xce, 0xcf, 0x77, 0x72, 0x03,
	0x47, 0xd9, 0xd2, 0x53, 0x98, 0x3f, 0x8f, 0x03, 0x74, 0xb3, 0x5c, 0x6a, 0xc9, 0x3b, 0xd9, 0xd2,
	0x7a, 0x2d, 0x92, 0x32, 0xba, 0x45, 0x8f, 0x3c, 0xcb, 0xe2, 0x2b, 0x4f, 0xc7, 0x09, 0x2a, 0x2d,
	0x92, 0xcc, 0x24, 0x59, 0x5f, 0x46, 0xb1, 0x5e, 0x15, 0x4b, 0x37, 0x90, 0x89, 0x17, 0xe5, 0x59,
	0x70, 0x86, 0x81, 0x54, 0x77, 0x4a, 0x63, 0x65, 0x46, 0x42, 0xe3, 0x5a, 0xdc, 0x79, 0x7a, 0x15,
	0xe7, 0xe1, 0x22, 0x13, 0xb9, 0xbe, 0xf3, 0x0c, 0xa7, 0xc8, 0x62, 0x55, 0x7d, 0x7a, 0x22, 0x8b,
	0x3d, 0x91, 0xa6, 0x52, 0x0b, 0x1d, 0xcb, 0x54, 0x55, 0xdc, 0x37, 0xff, 0x91, 0x9b, 0xb2, 0x83,
	0xb3, 0x08, 0xd3, 0x33, 0xb5, 0x16, 0x51, 0x84, 0xb9, 0x27, 0x33, 0x22, 0xda, 0x25, 0x75, 0xc6,
	0x70, 0xf8, 0xb9, 0xc2, 0x5c, 0xf9, 0xf8, 0x75, 0x81, 0x4a, 0x3b, 0x6f, 0xc0, 0x71, 0x69, 0x3f,
	0x93, 0x85, 0xc2, 0xda, 0xc9, 0xc7, 0xd0, 0x89, 0xc3, 0x09, 0xb3, 0xd9, 0x93, 0x81, 0xdf, 0x89,
	0x43, 0xe7, 0x7b, 0x06, 0x83, 0x26, 0x8b, 0xbf, 0x0c, 0x07, 0x85, 0xc2, 0x7c, 0xd1, 0xa4, 0xec,
	0x97, 0xe6, 0x3c, 0xe4, 0xaf, 0xc2, 0x80, 0x02, 0xa9, 0x48, 0x70, 0xd2, 0xa1, 0x50, 0xbf, 0x74,
	0x7c, 0x22, 0x12, 0xe4, 0xaf, 0x40, 0x7f, 0x55, 0xc2, 0x4b, 0x58, 0x97, 0x62, 0x07, 0x64, 0xcf,
	0x43, 0xfe, 0x26, 0x8c, 0x4d, 0xe8, 0x56, 0x06, 0xd4, 0xec, 0xa4, 0x47, 0x09, 0x23, 0xf2, 0x7e,
	0x5c, 0x39, 0x9d, 0xf7, 0x81, 0xb7, 0x5b, 0x55, 0x99, 0x4c, 0x15, 0x72, 0x17, 0x86, 0x54, 0x94,
	0x72, 0xd5, 0x84, 0xd9, 0xdd, 0x27, 0xc3, 0xe9, 0xc8, 0xcd, 0x96, 0x6e, 0x93, 0xec, 0x43, 0xd1,
	0xe0, 0x9c, 0x9f, 0x19, 0xf4, 0xca, 0xc8, 0xfd, 0x21, 0xf9, 0x3b, 0x00, 0x45, 0x16, 0x0a, 0x8d,
	0xe1, 0x42, 0x68, 0x6a, 0x7f, 0x38, 0xb5, 0x5c, 0xa3, 0x90, 0x5b, 0x1f, 0x80, 0xfb, 0x59, 0x7d,
	0x00, 0xfe, 0xa0, 0xca, 0xbe, 0xd2, 0x25, 0x34, 0xc8, 0xb1, 0x86, 0x76, 0xff, 0x1d, 0x5a, 0x65,
	0x5f, 0x69, 0xce, 0xa1, 0x47, 0xeb, 0x32, 0x13, 0xd3, 0xb7, 0xe3, 0xc1, 0xa8, 0xd2, 0xa8, 0x9a,
	0xf1, 0x31, 0xec, 0x95, 0x13, 0xd4, 0xd3, 0xf5, 0xeb, 0xe9, 0x7c, 0xe3, 0x76, 0xde, 0x82, 0xe3,
	0x6b, 0x62, 0x24, 0x67, 0x25, 0x62, 0xcd, 0xcc, 0x5a, 0xcc, 0x0f, 0x60, 0xb4, 0xa5, 0xb4, 0xf3,
	0x11, 0x70, 0x83, 0x34, 0x8b, 0xaa, 0xa0, 0x16, 0xf4, 0x1b, 0x29, 0x0c, 0xbc, 0xb1, 0x4b, 0x1d,
	0xe5, 0x3a, 0x35, 0xf2, 0x1b, 0x8d, 0x0f, 0xc8, 0x9e, 0x87, 0xce, 0x05, 0x8c, 0xef, 0x89, 0xf3,
	0x3a, 0xec, 0x6f, 0xe9, 0x32, 0x28, 0x3b, 0x37, 0xa5, 0xaa, 0x80, 0xf3, 0x1b, 0x83, 0x3d, 0x73,
	0x57, 0xff, 0x0f, 0x41, 0xda, 0xf3, 0xf5, 0xb6, 0xe6, 0xdb, 0x5a, 0xcb, 0xde, 0xf6, 0x5a, 0xa6,
	0x7f, 0x31, 0x18, 0x96, 0xdb, 0xbf, 0x31, 0x6f, 0x08, 0xbf, 0x86, 0xfe, 0x0c, 0x35, 0xc9, 0xc8,
	0x8f, 0x6a, 0xbd, 0xea, 0xb5, 0x5b, 0xc7, 0x2d, 0x8f, 0x59, 0x95, 0xc3, 0xbf, 0xfb, 0xfd, 0x8f,
	0x1f, 0x3b, 0x87, 0x1c, 0xe8, 0x35, 0x20, 0x5d, 0xf9, 0x35, 0x0c, 0x48, 0x1d, 0xba, 0xd7, 0x47,
	0x25, 0x66, 0x47, 0x66, 0xab, 0x39, 0x06, 0xe7, 0x11, 0x31, 0x3c, 0xb0, 0x5a, 0x0c, 0x4f, 0xd9,
	0x29, 0x5f, 0xc0, 0xb8, 0x0c, 0x7f, 0x11, 0xeb, 0x95, 0x51, 0xc7, 0x30, 0xed, 0xfc, 0xea, 0xad,
	0x93, 0xfb, 0xee, 0xaa, 0xb3, 0xc7, 0xc4, 0x3b, 0xe1, 0x27, 0x1b, 0x5e, 0xef, 0x9b, 0x38, 0xfc,
	0xd6, 0x33, 0x0a, 0x4e, 0xff, 0x64, 0x70, 0x48, 0x90, 0x7a, 0xf6, 0x19, 0x0c, 0x66, 0xa8, 0xab,
	0x62, 0xc7, 0x8d, 0xe4, 0x4d, 0x21, 0xde, 0x76, 0x55, 0x45, 0x1e, 0x52, 0x91, 0x11, 0x1f, 0x52,
	0x11, 0xc3, 0xcc, 0x3f, 0x84, 0xc3, 0x1b, 0x9d, 0xa3, 0x48, 0xfe, 0x99, 0x6b, 0x73, 0x51, 0x8e,
	0x45, 0x14, 0x2f, 0x71, 0xde, 0xa2, 0xf0, 0x14, 0xe1, 0xcf, 0x19, 0x7f, 0x06, 0xc3, 0xd6, 0xa5,
	0xf3, 0x93, 0xcd, 0x36, 0xdb, 0xa7, 0xdf, 0xe6, 0x3b, 0x21, 0xbe, 0x23, 0xab, 0xdd, 0xd2, 0x53,
	0x76, 0xfa, 0xde, 0xaf, 0xec, 0x87, 0xab, 0x5f, 0x18, 0xb7, 0xe0, 0xe1, 0x07, 0x2f, 0x44, 0x92,
	0xdd, 0xa2, 0x5d, 0xfd, 0x71, 0xd8, 0x22, 0x8b, 0xa7, 0xdd, 0xb7, 0xdd, 0xf3, 0x53, 0xd6, 0xf1,
	0x3f, 0x85, 0xee, 0xe5, 0xf9, 0x05, 0x9f, 0xc3, 0xcc, 0x47, 0x5d, 0xe4, 0x29, 0x86, 0xf6, 0x7a,
	0x85, 0xa9, 0xad, 0x57, 0x68, 0x97, 0x3b, 0xb4, 0x43, 0x89, 0xca, 0x4e, 0xa5, 0xb6, 0x57, 0xe2,
	0x39, 0xda, 0x19, 0xe6, 0x49, 0xac, 0x54, 0x2c, 0x53, 0x5b, 0x4b, 0x5b, 0x04, 0x01, 0x2a, 0x45,
	0xb9, 0x39, 0x2a, 0x59, 0xe4, 0x01, 0xba, 0xfe, 0xbb, 0x25, 0xe3, 0x25, 0xbf, 0x84, 0xd3, 0x5d,
	0xc6, 0x3a, 0x6b, 0xc3, 0x8a, 0x2f, 0x62, 0xa5, 0x5d, 0xbe, 0x0f, 0xbd, 0x9f, 0x3a, 0xec, 0x60,
	0xb9, 0x4f, 0x57, 0x7f, 0xf1, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x04, 0x37, 0x30, 0xe8,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	CreatUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	UserWithHouses(ctx context.Context, in *UserHousesRequest, opts ...grpc.CallOption) (*UserHousesResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/pb.UserService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreatUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/pb.UserService/CreatUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserWithHouses(ctx context.Context, in *UserHousesRequest, opts ...grpc.CallOption) (*UserHousesResponse, error) {
	out := new(UserHousesResponse)
	err := c.cc.Invoke(ctx, "/pb.UserService/UserWithHouses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUsers(context.Context, *UsersRequest) (*UsersResponse, error)
	CreatUser(context.Context, *CreateUserRequest) (*User, error)
	UserWithHouses(context.Context, *UserHousesRequest) (*UserHousesResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetUsers(ctx context.Context, req *UsersRequest) (*UsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedUserServiceServer) CreatUser(ctx context.Context, req *CreateUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatUser not implemented")
}
func (*UnimplementedUserServiceServer) UserWithHouses(ctx context.Context, req *UserHousesRequest) (*UserHousesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserWithHouses not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreatUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreatUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/CreatUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreatUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserWithHouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserHousesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserWithHouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/UserWithHouses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserWithHouses(ctx, req.(*UserHousesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
		{
			MethodName: "CreatUser",
			Handler:    _UserService_CreatUser_Handler,
		},
		{
			MethodName: "UserWithHouses",
			Handler:    _UserService_UserWithHouses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/service.proto",
}

// HouseServiceClient is the client API for HouseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HouseServiceClient interface {
	GetHouses(ctx context.Context, in *HousesRequest, opts ...grpc.CallOption) (*HousesResponse, error)
	StreamHouses(ctx context.Context, in *HousesRequest, opts ...grpc.CallOption) (HouseService_StreamHousesClient, error)
	CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*House, error)
}

type houseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHouseServiceClient(cc grpc.ClientConnInterface) HouseServiceClient {
	return &houseServiceClient{cc}
}

func (c *houseServiceClient) GetHouses(ctx context.Context, in *HousesRequest, opts ...grpc.CallOption) (*HousesResponse, error) {
	out := new(HousesResponse)
	err := c.cc.Invoke(ctx, "/pb.HouseService/GetHouses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseServiceClient) StreamHouses(ctx context.Context, in *HousesRequest, opts ...grpc.CallOption) (HouseService_StreamHousesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HouseService_serviceDesc.Streams[0], "/pb.HouseService/StreamHouses", opts...)
	if err != nil {
		return nil, err
	}
	x := &houseServiceStreamHousesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HouseService_StreamHousesClient interface {
	Recv() (*House, error)
	grpc.ClientStream
}

type houseServiceStreamHousesClient struct {
	grpc.ClientStream
}

func (x *houseServiceStreamHousesClient) Recv() (*House, error) {
	m := new(House)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *houseServiceClient) CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*House, error) {
	out := new(House)
	err := c.cc.Invoke(ctx, "/pb.HouseService/CreateHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HouseServiceServer is the server API for HouseService service.
type HouseServiceServer interface {
	GetHouses(context.Context, *HousesRequest) (*HousesResponse, error)
	StreamHouses(*HousesRequest, HouseService_StreamHousesServer) error
	CreateHouse(context.Context, *CreateHouseRequest) (*House, error)
}

// UnimplementedHouseServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHouseServiceServer struct {
}

func (*UnimplementedHouseServiceServer) GetHouses(ctx context.Context, req *HousesRequest) (*HousesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHouses not implemented")
}
func (*UnimplementedHouseServiceServer) StreamHouses(req *HousesRequest, srv HouseService_StreamHousesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamHouses not implemented")
}
func (*UnimplementedHouseServiceServer) CreateHouse(ctx context.Context, req *CreateHouseRequest) (*House, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHouse not implemented")
}

func RegisterHouseServiceServer(s *grpc.Server, srv HouseServiceServer) {
	s.RegisterService(&_HouseService_serviceDesc, srv)
}

func _HouseService_GetHouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HousesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseServiceServer).GetHouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HouseService/GetHouses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseServiceServer).GetHouses(ctx, req.(*HousesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseService_StreamHouses_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HousesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HouseServiceServer).StreamHouses(m, &houseServiceStreamHousesServer{stream})
}

type HouseService_StreamHousesServer interface {
	Send(*House) error
	grpc.ServerStream
}

type houseServiceStreamHousesServer struct {
	grpc.ServerStream
}

func (x *houseServiceStreamHousesServer) Send(m *House) error {
	return x.ServerStream.SendMsg(m)
}

func _HouseService_CreateHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseServiceServer).CreateHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.HouseService/CreateHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseServiceServer).CreateHouse(ctx, req.(*CreateHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HouseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.HouseService",
	HandlerType: (*HouseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHouses",
			Handler:    _HouseService_GetHouses_Handler,
		},
		{
			MethodName: "CreateHouse",
			Handler:    _HouseService_CreateHouse_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHouses",
			Handler:       _HouseService_StreamHouses_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/service.proto",
}
